/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.project.rds.myRds.Customer;
import org.xtext.project.rds.myRds.DeliveryDriver;
import org.xtext.project.rds.myRds.Menu;
import org.xtext.project.rds.myRds.MenuItem;
import org.xtext.project.rds.myRds.MyRdsPackage;
import org.xtext.project.rds.myRds.Order;
import org.xtext.project.rds.myRds.OrderItem;
import org.xtext.project.rds.myRds.RDS;
import org.xtext.project.rds.myRds.Restaurant;
import org.xtext.project.rds.myRds.Review;
import org.xtext.project.rds.myRds.User;
import org.xtext.project.rds.services.MyRdsGrammarAccess;

@SuppressWarnings("all")
public class MyRdsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyRdsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyRdsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyRdsPackage.CUSTOMER:
				sequence_Customer(context, (Customer) semanticObject); 
				return; 
			case MyRdsPackage.DELIVERY_DRIVER:
				sequence_DeliveryDriver(context, (DeliveryDriver) semanticObject); 
				return; 
			case MyRdsPackage.MENU:
				sequence_Menu(context, (Menu) semanticObject); 
				return; 
			case MyRdsPackage.MENU_ITEM:
				sequence_MenuItem(context, (MenuItem) semanticObject); 
				return; 
			case MyRdsPackage.ORDER:
				sequence_Order(context, (Order) semanticObject); 
				return; 
			case MyRdsPackage.ORDER_ITEM:
				sequence_OrderItem(context, (OrderItem) semanticObject); 
				return; 
			case MyRdsPackage.RDS:
				sequence_RDS(context, (RDS) semanticObject); 
				return; 
			case MyRdsPackage.RESTAURANT:
				sequence_Restaurant(context, (Restaurant) semanticObject); 
				return; 
			case MyRdsPackage.REVIEW:
				sequence_Review(context, (Review) semanticObject); 
				return; 
			case MyRdsPackage.USER:
				sequence_User(context, (User) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     UserRole returns Customer
	 *     Customer returns Customer
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Customer(ISerializationContext context, Customer semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.USER_ROLE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.USER_ROLE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCustomerAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     UserRole returns DeliveryDriver
	 *     DeliveryDriver returns DeliveryDriver
	 *
	 * Constraint:
	 *     (name=ID isAvailable?='isAvailable'? carLicenceNumber=STRING)
	 */
	protected void sequence_DeliveryDriver(ISerializationContext context, DeliveryDriver semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     MenuItem returns MenuItem
	 *
	 * Constraint:
	 *     (name=ID price=DECIMAL description=STRING category=MenuItemCategory)
	 */
	protected void sequence_MenuItem(ISerializationContext context, MenuItem semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.MENU_ITEM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.MENU_ITEM__NAME));
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.MENU_ITEM__PRICE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.MENU_ITEM__PRICE));
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.MENU_ITEM__DESCRIPTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.MENU_ITEM__DESCRIPTION));
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.MENU_ITEM__CATEGORY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.MENU_ITEM__CATEGORY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMenuItemAccess().getNameIDTerminalRuleCall_3_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getMenuItemAccess().getPriceDECIMALParserRuleCall_7_0(), semanticObject.getPrice());
		feeder.accept(grammarAccess.getMenuItemAccess().getDescriptionSTRINGTerminalRuleCall_11_0(), semanticObject.getDescription());
		feeder.accept(grammarAccess.getMenuItemAccess().getCategoryMenuItemCategoryEnumRuleCall_15_0(), semanticObject.getCategory());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Menu returns Menu
	 *
	 * Constraint:
	 *     (id=ID (menuItems+=MenuItem menuItems+=MenuItem*)?)
	 */
	protected void sequence_Menu(ISerializationContext context, Menu semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     OrderItem returns OrderItem
	 *
	 * Constraint:
	 *     (quantity=INT menuItem=[MenuItem|ID])
	 */
	protected void sequence_OrderItem(ISerializationContext context, OrderItem semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.ORDER_ITEM__QUANTITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.ORDER_ITEM__QUANTITY));
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.ORDER_ITEM__MENU_ITEM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.ORDER_ITEM__MENU_ITEM));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOrderItemAccess().getQuantityINTTerminalRuleCall_3_0(), semanticObject.getQuantity());
		feeder.accept(grammarAccess.getOrderItemAccess().getMenuItemMenuItemIDTerminalRuleCall_7_0_1(), semanticObject.eGet(MyRdsPackage.Literals.ORDER_ITEM__MENU_ITEM, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Order returns Order
	 *
	 * Constraint:
	 *     (
	 *         orderNumber=ID 
	 *         status=OrderStatus 
	 *         deliveryAddress=STRING 
	 *         customer=[Customer|ID] 
	 *         deliveryDriver=[DeliveryDriver|ID] 
	 *         orderedDatetime=DATETIME 
	 *         deliveredDatetime=DATETIME 
	 *         requestedDeliveryDatetime=DATETIME 
	 *         (orderItems+=OrderItem orderItems+=OrderItem*)? 
	 *         review+=Review?
	 *     )
	 */
	protected void sequence_Order(ISerializationContext context, Order semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     RDS returns RDS
	 *
	 * Constraint:
	 *     (
	 *         ((users+=User users+=User*)? restaurants+=Restaurant restaurants+=Restaurant* (orders+=Order orders+=Order*)) | 
	 *         ((users+=User users+=User*)? (orders+=Order orders+=Order*)) | 
	 *         (orders+=Order orders+=Order*)
	 *     )?
	 */
	protected void sequence_RDS(ISerializationContext context, RDS semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Restaurant returns Restaurant
	 *
	 * Constraint:
	 *     (name=ID address=STRING menu+=Menu)
	 */
	protected void sequence_Restaurant(ISerializationContext context, Restaurant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Review returns Review
	 *
	 * Constraint:
	 *     (id=ID numStars=INT description=STRING reviewDatetime=DATETIME)
	 */
	protected void sequence_Review(ISerializationContext context, Review semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.REVIEW__ID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.REVIEW__ID));
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.REVIEW__NUM_STARS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.REVIEW__NUM_STARS));
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.REVIEW__DESCRIPTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.REVIEW__DESCRIPTION));
			if (transientValues.isValueTransient(semanticObject, MyRdsPackage.Literals.REVIEW__REVIEW_DATETIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyRdsPackage.Literals.REVIEW__REVIEW_DATETIME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getReviewAccess().getIdIDTerminalRuleCall_1_0(), semanticObject.getId());
		feeder.accept(grammarAccess.getReviewAccess().getNumStarsINTTerminalRuleCall_5_0(), semanticObject.getNumStars());
		feeder.accept(grammarAccess.getReviewAccess().getDescriptionSTRINGTerminalRuleCall_9_0(), semanticObject.getDescription());
		feeder.accept(grammarAccess.getReviewAccess().getReviewDatetimeDATETIMEParserRuleCall_13_0(), semanticObject.getReviewDatetime());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     User returns User
	 *
	 * Constraint:
	 *     (fullName=STRING password=STRING phone=PHONE email=STRING (roles+=UserRole roles+=UserRole*)+)
	 */
	protected void sequence_User(ISerializationContext context, User semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
