/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.project.rds.services.MyRdsGrammarAccess;

@SuppressWarnings("all")
public class MyRdsSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyRdsGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Order_CommaKeyword_34_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyRdsGrammarAccess) access;
		match_Order_CommaKeyword_34_0_q = new TokenAlias(false, true, grammarAccess.getOrderAccess().getCommaKeyword_34_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Order_CommaKeyword_34_0_q.equals(syntax))
				emit_Order_CommaKeyword_34_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     orderItems+=OrderItem (ambiguity) '}' (rule end)
	 *     requestedDeliveryDatetime=DATETIME ',' 'ITEMS' ':' (ambiguity) '}' (rule end)
	 */
	protected void emit_Order_CommaKeyword_34_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
