/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyRdsUiModule extends AbstractMyRdsUiModule {

	public MyRdsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
