/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.project.rds.ide.contentassist.antlr.internal.InternalMyRdsParser;
import org.xtext.project.rds.services.MyRdsGrammarAccess;

public class MyRdsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyRdsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyRdsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUserRoleAccess().getAlternatives(), "rule__UserRole__Alternatives");
			builder.put(grammarAccess.getOrderStatusAccess().getAlternatives(), "rule__OrderStatus__Alternatives");
			builder.put(grammarAccess.getMenuItemCategoryAccess().getAlternatives(), "rule__MenuItemCategory__Alternatives");
			builder.put(grammarAccess.getRDSAccess().getGroup(), "rule__RDS__Group__0");
			builder.put(grammarAccess.getRDSAccess().getGroup_0(), "rule__RDS__Group_0__0");
			builder.put(grammarAccess.getRDSAccess().getGroup_0_1(), "rule__RDS__Group_0_1__0");
			builder.put(grammarAccess.getRDSAccess().getGroup_1(), "rule__RDS__Group_1__0");
			builder.put(grammarAccess.getRDSAccess().getGroup_1_1(), "rule__RDS__Group_1_1__0");
			builder.put(grammarAccess.getRDSAccess().getGroup_2(), "rule__RDS__Group_2__0");
			builder.put(grammarAccess.getRDSAccess().getGroup_2_1(), "rule__RDS__Group_2_1__0");
			builder.put(grammarAccess.getUserAccess().getGroup(), "rule__User__Group__0");
			builder.put(grammarAccess.getUserAccess().getGroup_18(), "rule__User__Group_18__0");
			builder.put(grammarAccess.getUserAccess().getGroup_18_1(), "rule__User__Group_18_1__0");
			builder.put(grammarAccess.getCustomerAccess().getGroup(), "rule__Customer__Group__0");
			builder.put(grammarAccess.getDeliveryDriverAccess().getGroup(), "rule__DeliveryDriver__Group__0");
			builder.put(grammarAccess.getOrderAccess().getGroup(), "rule__Order__Group__0");
			builder.put(grammarAccess.getOrderAccess().getGroup_33(), "rule__Order__Group_33__0");
			builder.put(grammarAccess.getOrderAccess().getGroup_33_1(), "rule__Order__Group_33_1__0");
			builder.put(grammarAccess.getRestaurantAccess().getGroup(), "rule__Restaurant__Group__0");
			builder.put(grammarAccess.getMenuAccess().getGroup(), "rule__Menu__Group__0");
			builder.put(grammarAccess.getMenuAccess().getGroup_5(), "rule__Menu__Group_5__0");
			builder.put(grammarAccess.getMenuAccess().getGroup_5_1(), "rule__Menu__Group_5_1__0");
			builder.put(grammarAccess.getMenuItemAccess().getGroup(), "rule__MenuItem__Group__0");
			builder.put(grammarAccess.getOrderItemAccess().getGroup(), "rule__OrderItem__Group__0");
			builder.put(grammarAccess.getReviewAccess().getGroup(), "rule__Review__Group__0");
			builder.put(grammarAccess.getDECIMALAccess().getGroup(), "rule__DECIMAL__Group__0");
			builder.put(grammarAccess.getFULLNAMEAccess().getGroup(), "rule__FULLNAME__Group__0");
			builder.put(grammarAccess.getPHONEAccess().getGroup(), "rule__PHONE__Group__0");
			builder.put(grammarAccess.getEMAILAccess().getGroup(), "rule__EMAIL__Group__0");
			builder.put(grammarAccess.getDATETIMEAccess().getGroup(), "rule__DATETIME__Group__0");
			builder.put(grammarAccess.getADDRESSAccess().getGroup(), "rule__ADDRESS__Group__0");
			builder.put(grammarAccess.getLICENCEAccess().getGroup(), "rule__LICENCE__Group__0");
			builder.put(grammarAccess.getRDSAccess().getUsersAssignment_0_0(), "rule__RDS__UsersAssignment_0_0");
			builder.put(grammarAccess.getRDSAccess().getUsersAssignment_0_1_1(), "rule__RDS__UsersAssignment_0_1_1");
			builder.put(grammarAccess.getRDSAccess().getRestaurantsAssignment_1_0(), "rule__RDS__RestaurantsAssignment_1_0");
			builder.put(grammarAccess.getRDSAccess().getRestaurantsAssignment_1_1_1(), "rule__RDS__RestaurantsAssignment_1_1_1");
			builder.put(grammarAccess.getRDSAccess().getOrdersAssignment_2_0(), "rule__RDS__OrdersAssignment_2_0");
			builder.put(grammarAccess.getRDSAccess().getOrdersAssignment_2_1_1(), "rule__RDS__OrdersAssignment_2_1_1");
			builder.put(grammarAccess.getUserAccess().getNameAssignment_4(), "rule__User__NameAssignment_4");
			builder.put(grammarAccess.getUserAccess().getPasswordAssignment_8(), "rule__User__PasswordAssignment_8");
			builder.put(grammarAccess.getUserAccess().getPhoneAssignment_12(), "rule__User__PhoneAssignment_12");
			builder.put(grammarAccess.getUserAccess().getEmailAssignment_16(), "rule__User__EmailAssignment_16");
			builder.put(grammarAccess.getUserAccess().getRolesAssignment_18_0(), "rule__User__RolesAssignment_18_0");
			builder.put(grammarAccess.getUserAccess().getRolesAssignment_18_1_1(), "rule__User__RolesAssignment_18_1_1");
			builder.put(grammarAccess.getCustomerAccess().getUsernameAssignment_1(), "rule__Customer__UsernameAssignment_1");
			builder.put(grammarAccess.getDeliveryDriverAccess().getUsernameAssignment_1(), "rule__DeliveryDriver__UsernameAssignment_1");
			builder.put(grammarAccess.getDeliveryDriverAccess().getIsAvailableAssignment_3(), "rule__DeliveryDriver__IsAvailableAssignment_3");
			builder.put(grammarAccess.getDeliveryDriverAccess().getCarLicenceNumberAssignment_7(), "rule__DeliveryDriver__CarLicenceNumberAssignment_7");
			builder.put(grammarAccess.getOrderAccess().getOrderNumberAssignment_1(), "rule__Order__OrderNumberAssignment_1");
			builder.put(grammarAccess.getOrderAccess().getStatusAssignment_5(), "rule__Order__StatusAssignment_5");
			builder.put(grammarAccess.getOrderAccess().getDeliveryAddressAssignment_9(), "rule__Order__DeliveryAddressAssignment_9");
			builder.put(grammarAccess.getOrderAccess().getCustomerAssignment_13(), "rule__Order__CustomerAssignment_13");
			builder.put(grammarAccess.getOrderAccess().getDeliveryDriverAssignment_17(), "rule__Order__DeliveryDriverAssignment_17");
			builder.put(grammarAccess.getOrderAccess().getOrderedDatetimeAssignment_21(), "rule__Order__OrderedDatetimeAssignment_21");
			builder.put(grammarAccess.getOrderAccess().getDeliveredDatetimeAssignment_25(), "rule__Order__DeliveredDatetimeAssignment_25");
			builder.put(grammarAccess.getOrderAccess().getRequestedDeliveryDatetimeAssignment_29(), "rule__Order__RequestedDeliveryDatetimeAssignment_29");
			builder.put(grammarAccess.getOrderAccess().getOrderItemsAssignment_33_0(), "rule__Order__OrderItemsAssignment_33_0");
			builder.put(grammarAccess.getOrderAccess().getOrderItemsAssignment_33_1_1(), "rule__Order__OrderItemsAssignment_33_1_1");
			builder.put(grammarAccess.getOrderAccess().getReviewAssignment_34(), "rule__Order__ReviewAssignment_34");
			builder.put(grammarAccess.getRestaurantAccess().getNameAssignment_1(), "rule__Restaurant__NameAssignment_1");
			builder.put(grammarAccess.getRestaurantAccess().getAddressAssignment_5(), "rule__Restaurant__AddressAssignment_5");
			builder.put(grammarAccess.getRestaurantAccess().getMenuAssignment_7(), "rule__Restaurant__MenuAssignment_7");
			builder.put(grammarAccess.getMenuAccess().getIdAssignment_1(), "rule__Menu__IdAssignment_1");
			builder.put(grammarAccess.getMenuAccess().getMenuItemsAssignment_5_0(), "rule__Menu__MenuItemsAssignment_5_0");
			builder.put(grammarAccess.getMenuAccess().getMenuItemsAssignment_5_1_1(), "rule__Menu__MenuItemsAssignment_5_1_1");
			builder.put(grammarAccess.getMenuItemAccess().getNameAssignment_3(), "rule__MenuItem__NameAssignment_3");
			builder.put(grammarAccess.getMenuItemAccess().getPriceAssignment_7(), "rule__MenuItem__PriceAssignment_7");
			builder.put(grammarAccess.getMenuItemAccess().getDescriptionAssignment_11(), "rule__MenuItem__DescriptionAssignment_11");
			builder.put(grammarAccess.getMenuItemAccess().getCategoryAssignment_15(), "rule__MenuItem__CategoryAssignment_15");
			builder.put(grammarAccess.getOrderItemAccess().getQuantityAssignment_3(), "rule__OrderItem__QuantityAssignment_3");
			builder.put(grammarAccess.getOrderItemAccess().getMenuItemAssignment_7(), "rule__OrderItem__MenuItemAssignment_7");
			builder.put(grammarAccess.getReviewAccess().getIdAssignment_1(), "rule__Review__IdAssignment_1");
			builder.put(grammarAccess.getReviewAccess().getNumStarsAssignment_5(), "rule__Review__NumStarsAssignment_5");
			builder.put(grammarAccess.getReviewAccess().getDescriptionAssignment_9(), "rule__Review__DescriptionAssignment_9");
			builder.put(grammarAccess.getReviewAccess().getReviewDatetimeAssignment_13(), "rule__Review__ReviewDatetimeAssignment_13");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyRdsGrammarAccess grammarAccess;

	@Override
	protected InternalMyRdsParser createParser() {
		InternalMyRdsParser result = new InternalMyRdsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyRdsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyRdsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
