/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyRdsStandaloneSetup extends MyRdsStandaloneSetupGenerated {

	public static void doSetup() {
		new MyRdsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
