/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.project.rds.parser.antlr.internal.InternalMyRdsParser;
import org.xtext.project.rds.services.MyRdsGrammarAccess;

public class MyRdsParser extends AbstractAntlrParser {

	@Inject
	private MyRdsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyRdsParser createParser(XtextTokenStream stream) {
		return new InternalMyRdsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MyRdsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyRdsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
