/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyRdsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/project/rds/parser/antlr/internal/InternalMyRds.tokens");
	}
}
