/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.project.rds.MyRdsRuntimeModule;
import org.xtext.project.rds.MyRdsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyRdsIdeSetup extends MyRdsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyRdsRuntimeModule(), new MyRdsIdeModule()));
	}
	
}
