/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Customer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getCustomer()
 * @model
 * @generated
 */
public interface Customer extends UserRole
{
} // Customer
