/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delivery Driver</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.DeliveryDriver#getIsAvailable <em>Is Available</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.DeliveryDriver#getCarLicenceNumber <em>Car Licence Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getDeliveryDriver()
 * @model
 * @generated
 */
public interface DeliveryDriver extends UserRole
{
  /**
   * Returns the value of the '<em><b>Is Available</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Available</em>' attribute.
   * @see #setIsAvailable(int)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getDeliveryDriver_IsAvailable()
   * @model
   * @generated
   */
  int getIsAvailable();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.DeliveryDriver#getIsAvailable <em>Is Available</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Available</em>' attribute.
   * @see #getIsAvailable()
   * @generated
   */
  void setIsAvailable(int value);

  /**
   * Returns the value of the '<em><b>Car Licence Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Car Licence Number</em>' attribute.
   * @see #setCarLicenceNumber(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getDeliveryDriver_CarLicenceNumber()
   * @model
   * @generated
   */
  String getCarLicenceNumber();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.DeliveryDriver#getCarLicenceNumber <em>Car Licence Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Car Licence Number</em>' attribute.
   * @see #getCarLicenceNumber()
   * @generated
   */
  void setCarLicenceNumber(String value);

} // DeliveryDriver
