/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.Menu#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Menu#getMenuItems <em>Menu Items</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenu()
 * @model
 * @generated
 */
public interface Menu extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenu_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Menu#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Menu Items</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.project.rds.myRds.MenuItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menu Items</em>' containment reference list.
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenu_MenuItems()
   * @model containment="true"
   * @generated
   */
  EList<MenuItem> getMenuItems();

} // Menu
