/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Menu Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.MenuItem#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.MenuItem#getPrice <em>Price</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.MenuItem#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.MenuItem#getCategory <em>Category</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.MenuItem#getOrderItems <em>Order Items</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.MenuItem#getMenu <em>Menu</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenuItem()
 * @model
 * @generated
 */
public interface MenuItem extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenuItem_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.MenuItem#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price</em>' attribute.
   * @see #setPrice(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenuItem_Price()
   * @model
   * @generated
   */
  String getPrice();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.MenuItem#getPrice <em>Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Price</em>' attribute.
   * @see #getPrice()
   * @generated
   */
  void setPrice(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenuItem_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.MenuItem#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Category</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.project.rds.myRds.MenuItemCategory}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category</em>' attribute.
   * @see org.xtext.project.rds.myRds.MenuItemCategory
   * @see #setCategory(MenuItemCategory)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenuItem_Category()
   * @model
   * @generated
   */
  MenuItemCategory getCategory();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.MenuItem#getCategory <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category</em>' attribute.
   * @see org.xtext.project.rds.myRds.MenuItemCategory
   * @see #getCategory()
   * @generated
   */
  void setCategory(MenuItemCategory value);

  /**
   * Returns the value of the '<em><b>Order Items</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project.rds.myRds.OrderItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order Items</em>' reference list.
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenuItem_OrderItems()
   * @model
   * @generated
   */
  EList<OrderItem> getOrderItems();

  /**
   * Returns the value of the '<em><b>Menu</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menu</em>' reference.
   * @see #setMenu(Menu)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenuItem_Menu()
   * @model
   * @generated
   */
  Menu getMenu();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.MenuItem#getMenu <em>Menu</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menu</em>' reference.
   * @see #getMenu()
   * @generated
   */
  void setMenu(Menu value);

} // MenuItem
