/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Menu Item Category</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenuItemCategory()
 * @model
 * @generated
 */
public enum MenuItemCategory implements Enumerator
{
  /**
   * The '<em><b>APPETIZER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #APPETIZER_VALUE
   * @generated
   * @ordered
   */
  APPETIZER(0, "APPETIZER", "appetizer"),

  /**
   * The '<em><b>SIDE DISH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIDE_DISH_VALUE
   * @generated
   * @ordered
   */
  SIDE_DISH(1, "SIDE_DISH", "side_dish"),

  /**
   * The '<em><b>MAIN DISH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAIN_DISH_VALUE
   * @generated
   * @ordered
   */
  MAIN_DISH(2, "MAIN_DISH", "main_dish"),

  /**
   * The '<em><b>DESSERT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DESSERT_VALUE
   * @generated
   * @ordered
   */
  DESSERT(3, "DESSERT", "dessert"),

  /**
   * The '<em><b>DRINK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DRINK_VALUE
   * @generated
   * @ordered
   */
  DRINK(4, "DRINK", "drink");

  /**
   * The '<em><b>APPETIZER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #APPETIZER
   * @model literal="appetizer"
   * @generated
   * @ordered
   */
  public static final int APPETIZER_VALUE = 0;

  /**
   * The '<em><b>SIDE DISH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIDE_DISH
   * @model literal="side_dish"
   * @generated
   * @ordered
   */
  public static final int SIDE_DISH_VALUE = 1;

  /**
   * The '<em><b>MAIN DISH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAIN_DISH
   * @model literal="main_dish"
   * @generated
   * @ordered
   */
  public static final int MAIN_DISH_VALUE = 2;

  /**
   * The '<em><b>DESSERT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DESSERT
   * @model literal="dessert"
   * @generated
   * @ordered
   */
  public static final int DESSERT_VALUE = 3;

  /**
   * The '<em><b>DRINK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DRINK
   * @model literal="drink"
   * @generated
   * @ordered
   */
  public static final int DRINK_VALUE = 4;

  /**
   * An array of all the '<em><b>Menu Item Category</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final MenuItemCategory[] VALUES_ARRAY =
    new MenuItemCategory[]
    {
      APPETIZER,
      SIDE_DISH,
      MAIN_DISH,
      DESSERT,
      DRINK,
    };

  /**
   * A public read-only list of all the '<em><b>Menu Item Category</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<MenuItemCategory> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Menu Item Category</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MenuItemCategory get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MenuItemCategory result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Menu Item Category</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MenuItemCategory getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MenuItemCategory result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Menu Item Category</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MenuItemCategory get(int value)
  {
    switch (value)
    {
      case APPETIZER_VALUE: return APPETIZER;
      case SIDE_DISH_VALUE: return SIDE_DISH;
      case MAIN_DISH_VALUE: return MAIN_DISH;
      case DESSERT_VALUE: return DESSERT;
      case DRINK_VALUE: return DRINK;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private MenuItemCategory(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //MenuItemCategory
