/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.Menu#getRestaurant <em>Restaurant</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Menu#getMenuItems <em>Menu Items</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenu()
 * @model
 * @generated
 */
public interface Menu extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Restaurant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Restaurant</em>' reference.
   * @see #setRestaurant(Restaurant)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenu_Restaurant()
   * @model
   * @generated
   */
  Restaurant getRestaurant();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Menu#getRestaurant <em>Restaurant</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Restaurant</em>' reference.
   * @see #getRestaurant()
   * @generated
   */
  void setRestaurant(Restaurant value);

  /**
   * Returns the value of the '<em><b>Menu Items</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project.rds.myRds.MenuItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menu Items</em>' reference list.
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getMenu_MenuItems()
   * @model
   * @generated
   */
  EList<MenuItem> getMenuItems();

} // Menu
