/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.project.rds.myRds.MyRdsFactory
 * @model kind="package"
 * @generated
 */
public interface MyRdsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myRds";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/project/rds/MyRds";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myRds";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyRdsPackage eINSTANCE = org.xtext.project.rds.myRds.impl.MyRdsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.RDSImpl <em>RDS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.RDSImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getRDS()
   * @generated
   */
  int RDS = 0;

  /**
   * The feature id for the '<em><b>Users</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDS__USERS = 0;

  /**
   * The feature id for the '<em><b>Restaurants</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDS__RESTAURANTS = 1;

  /**
   * The feature id for the '<em><b>Orders</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDS__ORDERS = 2;

  /**
   * The number of structural features of the '<em>RDS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.UserImpl <em>User</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.UserImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getUser()
   * @generated
   */
  int USER = 1;

  /**
   * The feature id for the '<em><b>Full Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__FULL_NAME = 0;

  /**
   * The feature id for the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__PASSWORD = 1;

  /**
   * The feature id for the '<em><b>Phone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__PHONE = 2;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__EMAIL = 3;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__ROLES = 4;

  /**
   * The number of structural features of the '<em>User</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.UserRoleImpl <em>User Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.UserRoleImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getUserRole()
   * @generated
   */
  int USER_ROLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_ROLE__NAME = 0;

  /**
   * The number of structural features of the '<em>User Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_ROLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.CustomerImpl <em>Customer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.CustomerImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getCustomer()
   * @generated
   */
  int CUSTOMER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMER__NAME = USER_ROLE__NAME;

  /**
   * The number of structural features of the '<em>Customer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMER_FEATURE_COUNT = USER_ROLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.DeliveryDriverImpl <em>Delivery Driver</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.DeliveryDriverImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getDeliveryDriver()
   * @generated
   */
  int DELIVERY_DRIVER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELIVERY_DRIVER__NAME = USER_ROLE__NAME;

  /**
   * The feature id for the '<em><b>Is Available</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELIVERY_DRIVER__IS_AVAILABLE = USER_ROLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Car Licence Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELIVERY_DRIVER__CAR_LICENCE_NUMBER = USER_ROLE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Delivery Driver</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELIVERY_DRIVER_FEATURE_COUNT = USER_ROLE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.OrderImpl <em>Order</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.OrderImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getOrder()
   * @generated
   */
  int ORDER = 5;

  /**
   * The feature id for the '<em><b>Order Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__ORDER_NUMBER = 0;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__STATUS = 1;

  /**
   * The feature id for the '<em><b>Delivery Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__DELIVERY_ADDRESS = 2;

  /**
   * The feature id for the '<em><b>Customer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__CUSTOMER = 3;

  /**
   * The feature id for the '<em><b>Delivery Driver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__DELIVERY_DRIVER = 4;

  /**
   * The feature id for the '<em><b>Ordered Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__ORDERED_DATETIME = 5;

  /**
   * The feature id for the '<em><b>Delivered Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__DELIVERED_DATETIME = 6;

  /**
   * The feature id for the '<em><b>Requested Delivery Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__REQUESTED_DELIVERY_DATETIME = 7;

  /**
   * The feature id for the '<em><b>Order Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__ORDER_ITEMS = 8;

  /**
   * The feature id for the '<em><b>Review</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__REVIEW = 9;

  /**
   * The number of structural features of the '<em>Order</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER_FEATURE_COUNT = 10;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.RestaurantImpl <em>Restaurant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.RestaurantImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getRestaurant()
   * @generated
   */
  int RESTAURANT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANT__NAME = 0;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANT__ADDRESS = 1;

  /**
   * The feature id for the '<em><b>Menu</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANT__MENU = 2;

  /**
   * The number of structural features of the '<em>Restaurant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.MenuImpl <em>Menu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.MenuImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getMenu()
   * @generated
   */
  int MENU = 7;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__ID = 0;

  /**
   * The feature id for the '<em><b>Menu Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__MENU_ITEMS = 1;

  /**
   * The number of structural features of the '<em>Menu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.MenuItemImpl <em>Menu Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.MenuItemImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getMenuItem()
   * @generated
   */
  int MENU_ITEM = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_ITEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_ITEM__PRICE = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_ITEM__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Category</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_ITEM__CATEGORY = 3;

  /**
   * The number of structural features of the '<em>Menu Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_ITEM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.OrderItemImpl <em>Order Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.OrderItemImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getOrderItem()
   * @generated
   */
  int ORDER_ITEM = 9;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER_ITEM__QUANTITY = 0;

  /**
   * The feature id for the '<em><b>Menu Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER_ITEM__MENU_ITEM = 1;

  /**
   * The number of structural features of the '<em>Order Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER_ITEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.impl.ReviewImpl <em>Review</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.impl.ReviewImpl
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getReview()
   * @generated
   */
  int REVIEW = 10;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__ID = 0;

  /**
   * The feature id for the '<em><b>Num Stars</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__NUM_STARS = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Review Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__REVIEW_DATETIME = 3;

  /**
   * The number of structural features of the '<em>Review</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.OrderStatus <em>Order Status</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.OrderStatus
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getOrderStatus()
   * @generated
   */
  int ORDER_STATUS = 11;

  /**
   * The meta object id for the '{@link org.xtext.project.rds.myRds.MenuItemCategory <em>Menu Item Category</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project.rds.myRds.MenuItemCategory
   * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getMenuItemCategory()
   * @generated
   */
  int MENU_ITEM_CATEGORY = 12;


  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.RDS <em>RDS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RDS</em>'.
   * @see org.xtext.project.rds.myRds.RDS
   * @generated
   */
  EClass getRDS();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project.rds.myRds.RDS#getUsers <em>Users</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Users</em>'.
   * @see org.xtext.project.rds.myRds.RDS#getUsers()
   * @see #getRDS()
   * @generated
   */
  EReference getRDS_Users();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project.rds.myRds.RDS#getRestaurants <em>Restaurants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Restaurants</em>'.
   * @see org.xtext.project.rds.myRds.RDS#getRestaurants()
   * @see #getRDS()
   * @generated
   */
  EReference getRDS_Restaurants();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project.rds.myRds.RDS#getOrders <em>Orders</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Orders</em>'.
   * @see org.xtext.project.rds.myRds.RDS#getOrders()
   * @see #getRDS()
   * @generated
   */
  EReference getRDS_Orders();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.User <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User</em>'.
   * @see org.xtext.project.rds.myRds.User
   * @generated
   */
  EClass getUser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.User#getFullName <em>Full Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Full Name</em>'.
   * @see org.xtext.project.rds.myRds.User#getFullName()
   * @see #getUser()
   * @generated
   */
  EAttribute getUser_FullName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.User#getPassword <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Password</em>'.
   * @see org.xtext.project.rds.myRds.User#getPassword()
   * @see #getUser()
   * @generated
   */
  EAttribute getUser_Password();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.User#getPhone <em>Phone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phone</em>'.
   * @see org.xtext.project.rds.myRds.User#getPhone()
   * @see #getUser()
   * @generated
   */
  EAttribute getUser_Phone();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.User#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see org.xtext.project.rds.myRds.User#getEmail()
   * @see #getUser()
   * @generated
   */
  EAttribute getUser_Email();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project.rds.myRds.User#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Roles</em>'.
   * @see org.xtext.project.rds.myRds.User#getRoles()
   * @see #getUser()
   * @generated
   */
  EReference getUser_Roles();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.UserRole <em>User Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Role</em>'.
   * @see org.xtext.project.rds.myRds.UserRole
   * @generated
   */
  EClass getUserRole();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.UserRole#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.project.rds.myRds.UserRole#getName()
   * @see #getUserRole()
   * @generated
   */
  EAttribute getUserRole_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.Customer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Customer</em>'.
   * @see org.xtext.project.rds.myRds.Customer
   * @generated
   */
  EClass getCustomer();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.DeliveryDriver <em>Delivery Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delivery Driver</em>'.
   * @see org.xtext.project.rds.myRds.DeliveryDriver
   * @generated
   */
  EClass getDeliveryDriver();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.DeliveryDriver#isIsAvailable <em>Is Available</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Available</em>'.
   * @see org.xtext.project.rds.myRds.DeliveryDriver#isIsAvailable()
   * @see #getDeliveryDriver()
   * @generated
   */
  EAttribute getDeliveryDriver_IsAvailable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.DeliveryDriver#getCarLicenceNumber <em>Car Licence Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Car Licence Number</em>'.
   * @see org.xtext.project.rds.myRds.DeliveryDriver#getCarLicenceNumber()
   * @see #getDeliveryDriver()
   * @generated
   */
  EAttribute getDeliveryDriver_CarLicenceNumber();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.Order <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Order</em>'.
   * @see org.xtext.project.rds.myRds.Order
   * @generated
   */
  EClass getOrder();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Order#getOrderNumber <em>Order Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Order Number</em>'.
   * @see org.xtext.project.rds.myRds.Order#getOrderNumber()
   * @see #getOrder()
   * @generated
   */
  EAttribute getOrder_OrderNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Order#getStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see org.xtext.project.rds.myRds.Order#getStatus()
   * @see #getOrder()
   * @generated
   */
  EAttribute getOrder_Status();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Order#getDeliveryAddress <em>Delivery Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Delivery Address</em>'.
   * @see org.xtext.project.rds.myRds.Order#getDeliveryAddress()
   * @see #getOrder()
   * @generated
   */
  EAttribute getOrder_DeliveryAddress();

  /**
   * Returns the meta object for the reference '{@link org.xtext.project.rds.myRds.Order#getCustomer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Customer</em>'.
   * @see org.xtext.project.rds.myRds.Order#getCustomer()
   * @see #getOrder()
   * @generated
   */
  EReference getOrder_Customer();

  /**
   * Returns the meta object for the reference '{@link org.xtext.project.rds.myRds.Order#getDeliveryDriver <em>Delivery Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Delivery Driver</em>'.
   * @see org.xtext.project.rds.myRds.Order#getDeliveryDriver()
   * @see #getOrder()
   * @generated
   */
  EReference getOrder_DeliveryDriver();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Order#getOrderedDatetime <em>Ordered Datetime</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ordered Datetime</em>'.
   * @see org.xtext.project.rds.myRds.Order#getOrderedDatetime()
   * @see #getOrder()
   * @generated
   */
  EAttribute getOrder_OrderedDatetime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Order#getDeliveredDatetime <em>Delivered Datetime</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Delivered Datetime</em>'.
   * @see org.xtext.project.rds.myRds.Order#getDeliveredDatetime()
   * @see #getOrder()
   * @generated
   */
  EAttribute getOrder_DeliveredDatetime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Order#getRequestedDeliveryDatetime <em>Requested Delivery Datetime</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Requested Delivery Datetime</em>'.
   * @see org.xtext.project.rds.myRds.Order#getRequestedDeliveryDatetime()
   * @see #getOrder()
   * @generated
   */
  EAttribute getOrder_RequestedDeliveryDatetime();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project.rds.myRds.Order#getOrderItems <em>Order Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Order Items</em>'.
   * @see org.xtext.project.rds.myRds.Order#getOrderItems()
   * @see #getOrder()
   * @generated
   */
  EReference getOrder_OrderItems();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project.rds.myRds.Order#getReview <em>Review</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Review</em>'.
   * @see org.xtext.project.rds.myRds.Order#getReview()
   * @see #getOrder()
   * @generated
   */
  EReference getOrder_Review();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.Restaurant <em>Restaurant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Restaurant</em>'.
   * @see org.xtext.project.rds.myRds.Restaurant
   * @generated
   */
  EClass getRestaurant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Restaurant#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.project.rds.myRds.Restaurant#getName()
   * @see #getRestaurant()
   * @generated
   */
  EAttribute getRestaurant_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Restaurant#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.xtext.project.rds.myRds.Restaurant#getAddress()
   * @see #getRestaurant()
   * @generated
   */
  EAttribute getRestaurant_Address();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project.rds.myRds.Restaurant#getMenu <em>Menu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Menu</em>'.
   * @see org.xtext.project.rds.myRds.Restaurant#getMenu()
   * @see #getRestaurant()
   * @generated
   */
  EReference getRestaurant_Menu();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.Menu <em>Menu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Menu</em>'.
   * @see org.xtext.project.rds.myRds.Menu
   * @generated
   */
  EClass getMenu();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Menu#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.project.rds.myRds.Menu#getId()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Id();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project.rds.myRds.Menu#getMenuItems <em>Menu Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Menu Items</em>'.
   * @see org.xtext.project.rds.myRds.Menu#getMenuItems()
   * @see #getMenu()
   * @generated
   */
  EReference getMenu_MenuItems();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.MenuItem <em>Menu Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Menu Item</em>'.
   * @see org.xtext.project.rds.myRds.MenuItem
   * @generated
   */
  EClass getMenuItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.MenuItem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.project.rds.myRds.MenuItem#getName()
   * @see #getMenuItem()
   * @generated
   */
  EAttribute getMenuItem_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.MenuItem#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Price</em>'.
   * @see org.xtext.project.rds.myRds.MenuItem#getPrice()
   * @see #getMenuItem()
   * @generated
   */
  EAttribute getMenuItem_Price();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.MenuItem#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.project.rds.myRds.MenuItem#getDescription()
   * @see #getMenuItem()
   * @generated
   */
  EAttribute getMenuItem_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.MenuItem#getCategory <em>Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Category</em>'.
   * @see org.xtext.project.rds.myRds.MenuItem#getCategory()
   * @see #getMenuItem()
   * @generated
   */
  EAttribute getMenuItem_Category();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.OrderItem <em>Order Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Order Item</em>'.
   * @see org.xtext.project.rds.myRds.OrderItem
   * @generated
   */
  EClass getOrderItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.OrderItem#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see org.xtext.project.rds.myRds.OrderItem#getQuantity()
   * @see #getOrderItem()
   * @generated
   */
  EAttribute getOrderItem_Quantity();

  /**
   * Returns the meta object for the reference '{@link org.xtext.project.rds.myRds.OrderItem#getMenuItem <em>Menu Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Menu Item</em>'.
   * @see org.xtext.project.rds.myRds.OrderItem#getMenuItem()
   * @see #getOrderItem()
   * @generated
   */
  EReference getOrderItem_MenuItem();

  /**
   * Returns the meta object for class '{@link org.xtext.project.rds.myRds.Review <em>Review</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Review</em>'.
   * @see org.xtext.project.rds.myRds.Review
   * @generated
   */
  EClass getReview();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Review#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.project.rds.myRds.Review#getId()
   * @see #getReview()
   * @generated
   */
  EAttribute getReview_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Review#getNumStars <em>Num Stars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num Stars</em>'.
   * @see org.xtext.project.rds.myRds.Review#getNumStars()
   * @see #getReview()
   * @generated
   */
  EAttribute getReview_NumStars();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Review#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.project.rds.myRds.Review#getDescription()
   * @see #getReview()
   * @generated
   */
  EAttribute getReview_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project.rds.myRds.Review#getReviewDatetime <em>Review Datetime</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Review Datetime</em>'.
   * @see org.xtext.project.rds.myRds.Review#getReviewDatetime()
   * @see #getReview()
   * @generated
   */
  EAttribute getReview_ReviewDatetime();

  /**
   * Returns the meta object for enum '{@link org.xtext.project.rds.myRds.OrderStatus <em>Order Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Order Status</em>'.
   * @see org.xtext.project.rds.myRds.OrderStatus
   * @generated
   */
  EEnum getOrderStatus();

  /**
   * Returns the meta object for enum '{@link org.xtext.project.rds.myRds.MenuItemCategory <em>Menu Item Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Menu Item Category</em>'.
   * @see org.xtext.project.rds.myRds.MenuItemCategory
   * @generated
   */
  EEnum getMenuItemCategory();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyRdsFactory getMyRdsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.RDSImpl <em>RDS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.RDSImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getRDS()
     * @generated
     */
    EClass RDS = eINSTANCE.getRDS();

    /**
     * The meta object literal for the '<em><b>Users</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDS__USERS = eINSTANCE.getRDS_Users();

    /**
     * The meta object literal for the '<em><b>Restaurants</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDS__RESTAURANTS = eINSTANCE.getRDS_Restaurants();

    /**
     * The meta object literal for the '<em><b>Orders</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDS__ORDERS = eINSTANCE.getRDS_Orders();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.UserImpl <em>User</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.UserImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getUser()
     * @generated
     */
    EClass USER = eINSTANCE.getUser();

    /**
     * The meta object literal for the '<em><b>Full Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER__FULL_NAME = eINSTANCE.getUser_FullName();

    /**
     * The meta object literal for the '<em><b>Password</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER__PASSWORD = eINSTANCE.getUser_Password();

    /**
     * The meta object literal for the '<em><b>Phone</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER__PHONE = eINSTANCE.getUser_Phone();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER__EMAIL = eINSTANCE.getUser_Email();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER__ROLES = eINSTANCE.getUser_Roles();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.UserRoleImpl <em>User Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.UserRoleImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getUserRole()
     * @generated
     */
    EClass USER_ROLE = eINSTANCE.getUserRole();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_ROLE__NAME = eINSTANCE.getUserRole_Name();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.CustomerImpl <em>Customer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.CustomerImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getCustomer()
     * @generated
     */
    EClass CUSTOMER = eINSTANCE.getCustomer();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.DeliveryDriverImpl <em>Delivery Driver</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.DeliveryDriverImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getDeliveryDriver()
     * @generated
     */
    EClass DELIVERY_DRIVER = eINSTANCE.getDeliveryDriver();

    /**
     * The meta object literal for the '<em><b>Is Available</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DELIVERY_DRIVER__IS_AVAILABLE = eINSTANCE.getDeliveryDriver_IsAvailable();

    /**
     * The meta object literal for the '<em><b>Car Licence Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DELIVERY_DRIVER__CAR_LICENCE_NUMBER = eINSTANCE.getDeliveryDriver_CarLicenceNumber();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.OrderImpl <em>Order</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.OrderImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getOrder()
     * @generated
     */
    EClass ORDER = eINSTANCE.getOrder();

    /**
     * The meta object literal for the '<em><b>Order Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORDER__ORDER_NUMBER = eINSTANCE.getOrder_OrderNumber();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORDER__STATUS = eINSTANCE.getOrder_Status();

    /**
     * The meta object literal for the '<em><b>Delivery Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORDER__DELIVERY_ADDRESS = eINSTANCE.getOrder_DeliveryAddress();

    /**
     * The meta object literal for the '<em><b>Customer</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDER__CUSTOMER = eINSTANCE.getOrder_Customer();

    /**
     * The meta object literal for the '<em><b>Delivery Driver</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDER__DELIVERY_DRIVER = eINSTANCE.getOrder_DeliveryDriver();

    /**
     * The meta object literal for the '<em><b>Ordered Datetime</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORDER__ORDERED_DATETIME = eINSTANCE.getOrder_OrderedDatetime();

    /**
     * The meta object literal for the '<em><b>Delivered Datetime</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORDER__DELIVERED_DATETIME = eINSTANCE.getOrder_DeliveredDatetime();

    /**
     * The meta object literal for the '<em><b>Requested Delivery Datetime</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORDER__REQUESTED_DELIVERY_DATETIME = eINSTANCE.getOrder_RequestedDeliveryDatetime();

    /**
     * The meta object literal for the '<em><b>Order Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDER__ORDER_ITEMS = eINSTANCE.getOrder_OrderItems();

    /**
     * The meta object literal for the '<em><b>Review</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDER__REVIEW = eINSTANCE.getOrder_Review();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.RestaurantImpl <em>Restaurant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.RestaurantImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getRestaurant()
     * @generated
     */
    EClass RESTAURANT = eINSTANCE.getRestaurant();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTAURANT__NAME = eINSTANCE.getRestaurant_Name();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTAURANT__ADDRESS = eINSTANCE.getRestaurant_Address();

    /**
     * The meta object literal for the '<em><b>Menu</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESTAURANT__MENU = eINSTANCE.getRestaurant_Menu();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.MenuImpl <em>Menu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.MenuImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getMenu()
     * @generated
     */
    EClass MENU = eINSTANCE.getMenu();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__ID = eINSTANCE.getMenu_Id();

    /**
     * The meta object literal for the '<em><b>Menu Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MENU__MENU_ITEMS = eINSTANCE.getMenu_MenuItems();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.MenuItemImpl <em>Menu Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.MenuItemImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getMenuItem()
     * @generated
     */
    EClass MENU_ITEM = eINSTANCE.getMenuItem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU_ITEM__NAME = eINSTANCE.getMenuItem_Name();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU_ITEM__PRICE = eINSTANCE.getMenuItem_Price();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU_ITEM__DESCRIPTION = eINSTANCE.getMenuItem_Description();

    /**
     * The meta object literal for the '<em><b>Category</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU_ITEM__CATEGORY = eINSTANCE.getMenuItem_Category();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.OrderItemImpl <em>Order Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.OrderItemImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getOrderItem()
     * @generated
     */
    EClass ORDER_ITEM = eINSTANCE.getOrderItem();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORDER_ITEM__QUANTITY = eINSTANCE.getOrderItem_Quantity();

    /**
     * The meta object literal for the '<em><b>Menu Item</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDER_ITEM__MENU_ITEM = eINSTANCE.getOrderItem_MenuItem();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.impl.ReviewImpl <em>Review</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.impl.ReviewImpl
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getReview()
     * @generated
     */
    EClass REVIEW = eINSTANCE.getReview();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVIEW__ID = eINSTANCE.getReview_Id();

    /**
     * The meta object literal for the '<em><b>Num Stars</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVIEW__NUM_STARS = eINSTANCE.getReview_NumStars();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVIEW__DESCRIPTION = eINSTANCE.getReview_Description();

    /**
     * The meta object literal for the '<em><b>Review Datetime</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVIEW__REVIEW_DATETIME = eINSTANCE.getReview_ReviewDatetime();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.OrderStatus <em>Order Status</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.OrderStatus
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getOrderStatus()
     * @generated
     */
    EEnum ORDER_STATUS = eINSTANCE.getOrderStatus();

    /**
     * The meta object literal for the '{@link org.xtext.project.rds.myRds.MenuItemCategory <em>Menu Item Category</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project.rds.myRds.MenuItemCategory
     * @see org.xtext.project.rds.myRds.impl.MyRdsPackageImpl#getMenuItemCategory()
     * @generated
     */
    EEnum MENU_ITEM_CATEGORY = eINSTANCE.getMenuItemCategory();

  }

} //MyRdsPackage
