/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Order</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getOrderNumber <em>Order Number</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getDeliveryAddress <em>Delivery Address</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getOrderedDatetime <em>Ordered Datetime</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getDeliveredDatetime <em>Delivered Datetime</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getRequestedDeliveryDatetime <em>Requested Delivery Datetime</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getOrderItems <em>Order Items</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getReview <em>Review</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getCustomer <em>Customer</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Order#getDeliveryDriver <em>Delivery Driver</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder()
 * @model
 * @generated
 */
public interface Order extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Order Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order Number</em>' attribute.
   * @see #setOrderNumber(int)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_OrderNumber()
   * @model
   * @generated
   */
  int getOrderNumber();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getOrderNumber <em>Order Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order Number</em>' attribute.
   * @see #getOrderNumber()
   * @generated
   */
  void setOrderNumber(int value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.project.rds.myRds.OrderStatus}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see org.xtext.project.rds.myRds.OrderStatus
   * @see #setStatus(OrderStatus)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_Status()
   * @model
   * @generated
   */
  OrderStatus getStatus();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see org.xtext.project.rds.myRds.OrderStatus
   * @see #getStatus()
   * @generated
   */
  void setStatus(OrderStatus value);

  /**
   * Returns the value of the '<em><b>Delivery Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delivery Address</em>' attribute.
   * @see #setDeliveryAddress(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_DeliveryAddress()
   * @model
   * @generated
   */
  String getDeliveryAddress();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getDeliveryAddress <em>Delivery Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delivery Address</em>' attribute.
   * @see #getDeliveryAddress()
   * @generated
   */
  void setDeliveryAddress(String value);

  /**
   * Returns the value of the '<em><b>Ordered Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ordered Datetime</em>' attribute.
   * @see #setOrderedDatetime(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_OrderedDatetime()
   * @model
   * @generated
   */
  String getOrderedDatetime();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getOrderedDatetime <em>Ordered Datetime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ordered Datetime</em>' attribute.
   * @see #getOrderedDatetime()
   * @generated
   */
  void setOrderedDatetime(String value);

  /**
   * Returns the value of the '<em><b>Delivered Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delivered Datetime</em>' attribute.
   * @see #setDeliveredDatetime(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_DeliveredDatetime()
   * @model
   * @generated
   */
  String getDeliveredDatetime();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getDeliveredDatetime <em>Delivered Datetime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delivered Datetime</em>' attribute.
   * @see #getDeliveredDatetime()
   * @generated
   */
  void setDeliveredDatetime(String value);

  /**
   * Returns the value of the '<em><b>Requested Delivery Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requested Delivery Datetime</em>' attribute.
   * @see #setRequestedDeliveryDatetime(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_RequestedDeliveryDatetime()
   * @model
   * @generated
   */
  String getRequestedDeliveryDatetime();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getRequestedDeliveryDatetime <em>Requested Delivery Datetime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Requested Delivery Datetime</em>' attribute.
   * @see #getRequestedDeliveryDatetime()
   * @generated
   */
  void setRequestedDeliveryDatetime(String value);

  /**
   * Returns the value of the '<em><b>Order Items</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project.rds.myRds.OrderItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order Items</em>' reference list.
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_OrderItems()
   * @model
   * @generated
   */
  EList<OrderItem> getOrderItems();

  /**
   * Returns the value of the '<em><b>Review</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Review</em>' reference.
   * @see #setReview(Review)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_Review()
   * @model
   * @generated
   */
  Review getReview();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getReview <em>Review</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Review</em>' reference.
   * @see #getReview()
   * @generated
   */
  void setReview(Review value);

  /**
   * Returns the value of the '<em><b>Customer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Customer</em>' reference.
   * @see #setCustomer(Customer)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_Customer()
   * @model
   * @generated
   */
  Customer getCustomer();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getCustomer <em>Customer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Customer</em>' reference.
   * @see #getCustomer()
   * @generated
   */
  void setCustomer(Customer value);

  /**
   * Returns the value of the '<em><b>Delivery Driver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delivery Driver</em>' reference.
   * @see #setDeliveryDriver(DeliveryDriver)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrder_DeliveryDriver()
   * @model
   * @generated
   */
  DeliveryDriver getDeliveryDriver();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Order#getDeliveryDriver <em>Delivery Driver</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delivery Driver</em>' reference.
   * @see #getDeliveryDriver()
   * @generated
   */
  void setDeliveryDriver(DeliveryDriver value);

} // Order
