/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Order Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.OrderItem#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.OrderItem#getForOrder <em>For Order</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.OrderItem#getMenuItem <em>Menu Item</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrderItem()
 * @model
 * @generated
 */
public interface OrderItem extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrderItem_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.OrderItem#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>For Order</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>For Order</em>' reference.
   * @see #setForOrder(Order)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrderItem_ForOrder()
   * @model
   * @generated
   */
  Order getForOrder();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.OrderItem#getForOrder <em>For Order</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>For Order</em>' reference.
   * @see #getForOrder()
   * @generated
   */
  void setForOrder(Order value);

  /**
   * Returns the value of the '<em><b>Menu Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menu Item</em>' reference.
   * @see #setMenuItem(MenuItem)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getOrderItem_MenuItem()
   * @model
   * @generated
   */
  MenuItem getMenuItem();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.OrderItem#getMenuItem <em>Menu Item</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menu Item</em>' reference.
   * @see #getMenuItem()
   * @generated
   */
  void setMenuItem(MenuItem value);

} // OrderItem
