/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RDS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.RDS#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getRDS()
 * @model
 * @generated
 */
public interface RDS extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.project.rds.myRds.AbstractElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getRDS_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractElement> getElements();

} // RDS
