/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Review</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.Review#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Review#getNumStars <em>Num Stars</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Review#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.Review#getReviewDatetime <em>Review Datetime</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getReview()
 * @model
 * @generated
 */
public interface Review extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getReview_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Review#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Num Stars</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num Stars</em>' attribute.
   * @see #setNumStars(int)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getReview_NumStars()
   * @model
   * @generated
   */
  int getNumStars();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Review#getNumStars <em>Num Stars</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num Stars</em>' attribute.
   * @see #getNumStars()
   * @generated
   */
  void setNumStars(int value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getReview_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Review#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Review Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Review Datetime</em>' attribute.
   * @see #setReviewDatetime(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getReview_ReviewDatetime()
   * @model
   * @generated
   */
  String getReviewDatetime();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.Review#getReviewDatetime <em>Review Datetime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Review Datetime</em>' attribute.
   * @see #getReviewDatetime()
   * @generated
   */
  void setReviewDatetime(String value);

} // Review
