/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.User#getFullName <em>Full Name</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.User#getPassword <em>Password</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.User#getPhone <em>Phone</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.User#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.project.rds.myRds.User#getRoles <em>Roles</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getUser()
 * @model
 * @generated
 */
public interface User extends EObject
{
  /**
   * Returns the value of the '<em><b>Full Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Full Name</em>' attribute.
   * @see #setFullName(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getUser_FullName()
   * @model
   * @generated
   */
  String getFullName();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.User#getFullName <em>Full Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Full Name</em>' attribute.
   * @see #getFullName()
   * @generated
   */
  void setFullName(String value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' attribute.
   * @see #setPassword(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getUser_Password()
   * @model
   * @generated
   */
  String getPassword();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.User#getPassword <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' attribute.
   * @see #getPassword()
   * @generated
   */
  void setPassword(String value);

  /**
   * Returns the value of the '<em><b>Phone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phone</em>' attribute.
   * @see #setPhone(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getUser_Phone()
   * @model
   * @generated
   */
  String getPhone();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.User#getPhone <em>Phone</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phone</em>' attribute.
   * @see #getPhone()
   * @generated
   */
  void setPhone(String value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getUser_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.xtext.project.rds.myRds.User#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Roles</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.project.rds.myRds.UserRole}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roles</em>' containment reference list.
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getUser_Roles()
   * @model containment="true"
   * @generated
   */
  EList<UserRole> getRoles();

} // User
