/**
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.myRds;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User Role</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.rds.myRds.UserRole#getOrders <em>Orders</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.rds.myRds.MyRdsPackage#getUserRole()
 * @model
 * @generated
 */
public interface UserRole extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Orders</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project.rds.myRds.Order}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Orders</em>' reference list.
   * @see org.xtext.project.rds.myRds.MyRdsPackage#getUserRole_Orders()
   * @model
   * @generated
   */
  EList<Order> getOrders();

} // UserRole
