/*
 * generated by Xtext 2.25.0
 */
package org.xtext.project.rds.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyRdsScopeProvider extends DelegatingScopeProvider {
}
